services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    container_name: devops-app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-server
