---
- name: Local development setup
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Ensure Git is installed
      homebrew:
        name: git
        state: present

    - name: Ensure Node.js is installed
      homebrew:
        name: node
        state: present
          
    - name: Install app dependencies
      ansible.builtin.command: npm install
      args:
        chdir: "{{ playbook_dir }}"

    - name: Start the app
      ansible.builtin.command: npm start
      args:
        chdir: "{{ playbook_dir }}"
      async: 600
      poll: 0

    - name: Print success message
      debug:
        msg: "Ansible finished setting up your dev environment!"


